- name: Setup Buildozer and Cython
      run: |
        pip install --upgrade pip==24.0
        pip install --upgrade setuptools
        # Buildozerのバージョンを安定している 1.5.0 に固定する
        pip install buildozer==1.5.0 cython==0.29.36
